require = ["a"]
components = ["b", "c"]
extensions = ["js", "json"]

[environments.dev]
require = ["d", "e"]
components = ["f", "g"]

[environments.prod]
require = ["h"]
components = ["i", "j"]

[paths.environment]
global = "k"
component = "l"
